### ISSUE TITLE
question

### ISSUE THREAD

**Issue by dcsan** [Askrround/botly#5]
hey - just found this here. very interesting and good to see you implement the full FB APIs.

do you plan to add anything for conversations etc? like botkit and msbot framework?

**Comment by miki2826** [comment]
Hi @dcsan - thanks!,
I don't think it is necessary to implement something that botkit already did. 
I provide a more low level sdk that you can use to create your own higher level sdk or use as is.
That being said, if I'll see demand for it, I will consider it :)

**Comment by dcsan** [comment]
yea, could be right. well maybe some example integration with a api.ai or other "conversation system" or NLP tools could be helpful...

are you just coding your bots using raw regexes? managing conversation state is quite a pain...

**Comment by miki2826** [comment]
I integrate today with WIT.ai. But I use it for NLP only.
I do manage the conversation state myself - it is a small pain but it is consistent and I have full control over it.

I will add some integration examples soon, thanks.

**Comment by dcsan** [comment]
yes control is good ;)

I had some problems when in the middle of a bot kit conversation, and a menu event comes in from somewhere - ie not a conversation event. it's hard to exit the conversation. ms bot framework seems a bit more flexible for changing state to jump *across* trees, not just out of the loop.

**Comment by chiransudha** [comment]
@miki2826 Hi Miki 2826 can you please post integration to wi.ai example. I am trying to integrate to wit.ai but kinda new to this.
 Thank you.

**Comment by miki2826** [comment]
Hi @chiransudha ,

There are few ways to use WIT API.
- The message API (for entity extraction)
```javascript
const botly = new Botly({
    accessToken: "FACEBOOK_ACCESS_TOKEN"
    verifyToken: 'VERIFICATION_TOKEN'
});
const client = new Wit({accessToken: 'MY_TOKEN'});
botly.on('message', (sender, message, data) => {
   client.message(data.text, {})
   .then((data) => {
      console.log('Yay, got Wit.ai response: ' + JSON.stringify(data));
   })
   .catch(console.error);
});
```

- The bot engine way
Take a look at the WIT facebook messenger example: https://github.com/wit-ai/node-wit/blob/master/examples/messenger.js

With botly you can save the whole wiring with express and just call `wit.runActions` on message.
Also, replace the `send` action implementation with your own using `botly.sendText` for example
